# Generated by Django 5.0.2 on 2024-10-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.CharField(choices=[('active', 'Active'), ('in_active', 'In_active')], max_length=10),
        ),
    ]
