# Generated by Django 5.0.2 on 2024-10-18 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='device_images')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='device_images')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='device_images')),
                ('name', models.CharField(max_length=100)),
                ('imei1', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('imei2', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('last_known_location', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
