# Generated by Django 5.0.2 on 2024-10-19 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='device',
            name='last_known_location',
        ),
    ]
